name: Certora

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jre

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Install solc 0.8.24
        run: solc-select install 0.8.24

      - name: Install Certora
        run: pip3 install certora-cli

      - name: Certora verify Counter
        run: make certora-counter
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
